---
# The playbook deploys JupyterHub.
# This file would be equivalent to a `sites.yml` file in Ansible terms.

- hosts: jupyterhub_hosts
  tasks:
    - assert:
        that: (ansible_version.major, ansible_version.minor) >= (2, 1)
        msg: require ansible >= 2.1, found {{ansible_version.full}}

    - command: echo "$PATH"
      register: default_path


#- hosts: jupyterhub_hosts
#  tasks:
#   - name: Make sure we are running on Ubuntu
#     fail: msg="This ansible setup only work on Ubuntu"
#     when: ansible_distribution != 'Ubuntu' 


- hosts: jupyterhub_hosts
  roles:
    - common
    - postgres
    - python
    - role: r
      when: install_r_kernel is defined and install_r_kernel
    - role: newrelic
      when: newrelic_license_key is defined and newrelic_license_key != ''
    - nginx
    - supervisor
    - role: jupyterlab
      when: use_jupyterlab is defined and use_jupyterlab
    - role: remotekernel
      when: use_remotekernel is defined and use_remotekernel
    - role: nbexamples
      when: use_nbexamples is defined and use_nbexamples
    # - saveusers
    # - role: bash
    #   when: install_bash_kernel is defined and install_bash_kernel
    - jupyterhub
    - role: cull_idle
      when: use_cull_idle_servers is defined and use_cull_idle_servers
    # - role: nbgrader
    #   when: use_nbgrader is defined and use_nbgrader
    - kernels
    - role: start_jupyterhub
  environment:
      PATH: "/opt/conda/bin:{{ default_path.stdout }}"
      http_proxy: http://proxy:8888
      https_proxy: http://proxy:8888
      no_proxy: cs.nsls2.local,127.0.0.1,localhost
