---

- name: make sure beamline_kernels_dir exists
  file: path={{ beamline_kernels_dir }}/ state={{item}} owner=root group=root mode=0755
  become: true
  with_items:
    - directory
    - touch

- name: sync beamline kernels
  synchronize:
    src: ../files/
    dest: "{{ beamline_kernels_dir }}"

- name: disable requirement of default 'Python 3' kernel
  lineinfile:
    dest: /etc/jupyter/jupyter_notebook_config.py
    state: present
    line: 'c.KernelSpecManager.ensure_native_kernel=False'
    create: yes

- name: remove default 'Python 3' kernel
  shell: conda remove ipykernel --force && jupyter kernelspec remove -f python3
