---
- name: ensure packages are installed
  apt: name={{item}}
  with_items:
      - postgresql
      - libpq-dev
      - python3-psycopg2

- name: Create postgres user
  postgresql_user: name={{ pg_user }} password={{ pg_password }}
  become: true
  become_user: postgres

- name: create postgres database for jupyterhub state
  postgresql_db:
    name: jupyterhub_db
  become: true
  become_user: postgres
