- name: disable requirement of default 'Python 3' kernel
  lineinfile:
    dest: /etc/jupyter/jupyter_notebook_config.py
    state: present
    line: 'c.KernelSpecManager.ensure_native_kernel=False'
    create: yes

- name: remove default 'Python 3' kernel
  shell: conda remove ipykernel --force && jupyter kernelspec remove -f python3

- name: make sure /opt/jupyter exists
  file: path=/opt/jupyter/{{ item.sector }}/kernels/{{ item.name }} state=directory owner=root group=root mode=0755
  become: true
  with_items: "{{ kernelspecs }}"

- name: create system-level kernel specs
  template: src=kernel.json.j2 dest=/opt/jupyter/{{ item.sector }}/kernels/{{ item.name }}/kernel.json owner=root group=root mode=0644
  become: true
  with_items: "{{ kernelspecs }}"
